// <auto-generated />
using System;
using EFTesting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFTesting.Migrations
{
    [DbContext(typeof(MachineContext))]
    [Migration("20190517200645_InitialModel")]
    partial class InitialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFTesting.Models.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MachineID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GeneralRole")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("InstalledRoles")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("MachineTypeId")
                        .HasColumnName("MachineTypeID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<int>("OperatingSysId")
                        .HasColumnName("OperatingSysID");

                    b.HasKey("MachineId");

                    b.HasIndex("MachineTypeId");

                    b.HasIndex("OperatingSysId");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("EFTesting.Models.MachineType", b =>
                {
                    b.Property<int>("MachineTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MachineTypeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("MachineTypeId");

                    b.ToTable("MachineType");
                });

            modelBuilder.Entity("EFTesting.Models.MachineWarranty", b =>
                {
                    b.Property<int>("MachineWarrantyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MachineWarrantyID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MachineId")
                        .HasColumnName("MachineID");

                    b.Property<string>("ServiceTag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<DateTime>("WarrantyExpiration")
                        .HasColumnName("date");

                    b.Property<int>("WarrantyProviderId")
                        .HasColumnName("WarrantyProviderID");

                    b.HasKey("MachineWarrantyId");

                    b.HasIndex("WarrantyProviderId");

                    b.ToTable("MachineWarranty");
                });

            modelBuilder.Entity("EFTesting.Models.OperatingSys", b =>
                {
                    b.Property<int>("OperatingSysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OperatingSysID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(true);

                    b.Property<bool>("StillSupported");

                    b.HasKey("OperatingSysId");

                    b.ToTable("OperatingSys");
                });

            modelBuilder.Entity("EFTesting.Models.SupportLog", b =>
                {
                    b.Property<int>("SupportLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SupportLogID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SupportLogEntry")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<DateTime>("SupportLogEntryDate")
                        .HasColumnType("date");

                    b.Property<string>("SupportLogUpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("SupportTicketId")
                        .HasColumnName("SupportTicketID");

                    b.HasKey("SupportLogId");

                    b.HasIndex("SupportTicketId");

                    b.ToTable("SupportLog");
                });

            modelBuilder.Entity("EFTesting.Models.SupportTicket", b =>
                {
                    b.Property<int>("SupportTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SupportTicketID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateReported")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateResolved")
                        .HasColumnType("date");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("IssueDetail");

                    b.Property<int>("MachineId")
                        .HasColumnName("MachineID");

                    b.Property<string>("TicketOpenedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("SupportTicketId");

                    b.HasIndex("MachineId");

                    b.ToTable("SupportTicket");
                });

            modelBuilder.Entity("EFTesting.Models.WarrantyProvider", b =>
                {
                    b.Property<int>("WarrantyProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("WarrantyProviderID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("SupportExtension");

                    b.Property<string>("SupportNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("WarrantyProviderId");

                    b.ToTable("WarrantyProvider");
                });

            modelBuilder.Entity("EFTesting.Models.Machine", b =>
                {
                    b.HasOne("EFTesting.Models.MachineType", "MachineType")
                        .WithMany("Machine")
                        .HasForeignKey("MachineTypeId")
                        .HasConstraintName("FK_MachineType")
                        .IsRequired();

                    b.HasOne("EFTesting.Models.OperatingSys", "OperatingSys")
                        .WithMany("Machine")
                        .HasForeignKey("OperatingSysId")
                        .IsRequired();
                });

            modelBuilder.Entity("EFTesting.Models.MachineWarranty", b =>
                {
                    b.HasOne("EFTesting.Models.WarrantyProvider", "WarrantyProvider")
                        .WithMany("MachineWarranty")
                        .HasForeignKey("WarrantyProviderId")
                        .HasConstraintName("FK_WarrantyProvider")
                        .IsRequired();
                });

            modelBuilder.Entity("EFTesting.Models.SupportLog", b =>
                {
                    b.HasOne("EFTesting.Models.SupportTicket", "SupportTicket")
                        .WithMany("SupportLog")
                        .HasForeignKey("SupportTicketId")
                        .HasConstraintName("FK_SupportTicket")
                        .IsRequired();
                });

            modelBuilder.Entity("EFTesting.Models.SupportTicket", b =>
                {
                    b.HasOne("EFTesting.Models.Machine", "Machine")
                        .WithMany("SupportTicket")
                        .HasForeignKey("MachineId")
                        .HasConstraintName("FK_Machine")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
